name       : seahorse-nautilus
version    : 3.11.92
release    : 3
source     :
    - https://download.gnome.org/sources/seahorse-nautilus/3.11/seahorse-nautilus-3.11.92.tar.xz : 70374f9bb46a0adfbd154f4094e7a05b7766abfe60845a0a49463b4d15f17f92
license    : GPL-2.0
component  : security.crypto
summary    : Encryption extension for Nautilus
description: |
    Seahorse nautilus is an extension for Nautilus which allows encryption and decryption of OpenPGP files using GnuPG.
builddeps  :
    - pkgconfig(cryptui-0.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - gnupg
    - gpgme-devel
    - libassuan-devel
setup      : |
    sed -i 's:1.2 1.4 2.0:2.1:g' configure.ac
    %reconfigure
build      : |
    %make
install    : |
    %make_install
