name       : seahorse-nautilus
version    : 3.11.92
release    : 6
source     :
    - git|https://git.gnome.org/browse/seahorse-nautilus : 54ed5f3b51c8954a2d4f2ab65e0a2c2a780331c4
license    : GPL-2.0
component  : security.crypto
summary    : Encryption extension for Nautilus
description: |
    Seahorse nautilus is an extension for Nautilus which allows encryption and decryption of OpenPGP files using GnuPG.
builddeps  :
    - pkgconfig(cryptui-0.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnautilus-extension)
    - gnupg
    - gpgme-devel
    - libassuan-devel
setup      : |
    %meson_configure -Dlibnotify=false
build      : |
    %ninja_build
install    : |
    %ninja_install
