name       : seahorse-nautilus
version    : 3.11.92
release    : 11
source     :
    - git|https://gitlab.gnome.org/GNOME/seahorse-nautilus.git : 03d33bc03ddf3566da23b2cd6dea313b62749945
license    : GPL-2.0
component  : security.crypto
summary    : Encryption extension for Nautilus
description: |
    Seahorse nautilus is an extension for Nautilus which allows encryption and decryption of OpenPGP files using GnuPG.
builddeps  :
    - pkgconfig(cryptui-0.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libassuan)
    - pkgconfig(libnautilus-extension)
    - gnupg
setup      : |
    %meson_configure -Dlibnotify=false
build      : |
    %ninja_build
install    : |
    %ninja_install
