name       : seahorse-nautilus
version    : 3.11.92
release    : 15
source     :
    - git|https://gitlab.gnome.org/GNOME/seahorse-nautilus.git : 2cc2a06148604b2f118ef460527b03d27530f6d4
license    : GPL-2.0-or-later
component  : security.crypto
summary    : Encryption extension for Nautilus
description: |
    Seahorse nautilus is an extension for Nautilus which allows encryption and decryption of OpenPGP files using GnuPG.
builddeps  :
    - pkgconfig(cryptui-0.0)
    - pkgconfig(gcr-3)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gpgme)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libassuan)
    - pkgconfig(libnautilus-extension-4)
    - gnupg
setup      : |
    %meson_configure -Dlibnotify=false
build      : |
    %ninja_build
install    : |
    %ninja_install
